# Generated by Django 4.2 on 2023-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldloancompany',
            name='processing_fee',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
